server:
    port: ${SERVER_PORT:8080}
spring:
    redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:admin}

jag:
    efiling:
        navigation:
            baseUrl: ${NAVIGATION_BASE_URL:https://httpbin.org/}
            expirytime: ${NAVIGATION_EXPIRYTIME:10}

info:
    app:
        name: @project.name@
        description: @project.description@
        version: @project.version@
