version: 2
updates:
  # Mvn dependencies
  - package-ecosystem: "maven"
    directory: "/src/backend"
    schedule:
      interval: "daily"
      time: "18:00"
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "daily"
      time: "18:00"
