version: "2"

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
      tests_patterns:
        - src/backend/**/test/**
  eslint:
    enabled: true
    config:
      config: src/frontend/efiling-frontend/.eslintrc.js
  pmd:
    enabled: true

checks:
  similar-code:
    enabled: false

exclude_patterns:
- "src/frontend/efiling-demo/src/*.js"
- "src/frontend/efiling-frontend/src/*.js"
- "src/frontend/efiling-demo/public/"
- "src/frontend/efiling-frontend/public/"
- "src/frontend/efiling-demo/.storybook/"
- "src/frontend/efiling-frontend/.storybook/"
- "src/backend/jag-efiling-api/src/main/java/ca/bc/gov/open/jagefilingapi/cache/CacheConfiguration.java"

