version: '3.7'
services:

#############################################################################################
###                           JAG File Submission service                                 ###
#############################################################################################
    jag-file-submission:
        build:
            context: ./jag-efiling-api
            args:
            - SERVICE_NAME=jag-efiling-api
            - MVN_PROFILES=openshift
        ports:
            - "8080:8080"
