openapi: 3.0.0
info:
  version: 0.3.0
  title: jag-efiling-api
  description: Efiling api
servers:
- url: 'http://localhost/8080'
tags:
- name: document
  description: Document Api
paths:
  '/document/generateUrl':
    post:
      summary: Generates a secure URL for e-filing document
      operationId: GenerateUrl
      tags:
      - document
      requestBody:
        description: requested parameters to generate a url
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateUrlRequest'
      responses:
        '200':
          description: File successfully received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateUrlResponse'
components:
  schemas:
    GenerateUrlRequest:
      description: details about the required transaction
      required:
      - navigation
      properties:
        navigation:
          $ref: '#/components/schemas/Navigation'
    GenerateUrlResponse:
      description: A temporary url for uploading documents
      properties:
        expiryDate:
          type: long
        eFilingUrl:
          type: string
    Navigation:
      required:
      - success
      - error
      - cancel
      properties:
        success:
          $ref: '#/components/schemas/Redirect'
        error:
          $ref: '#/components/schemas/Redirect'
        cancel:
          $ref: '#/components/schemas/Redirect'
    Redirect:
      required:
      - url
      properties:
        url:
          type: string