openapi: 3.0.0
info:
  version: 0.3.0
  title: jag-efiling-api
  description: Efiling api
servers:
- url: 'http://localhost:8080'
tags:
- name: document
  description: Document Api
paths:
  '/document/generateUrl':
    post:
      summary: Generates a secure URL for e-filing document
      operationId: GenerateUrl
      tags:
      - document
      requestBody:
        description: requested parameters to generate a url
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateUrlRequest'
      responses:
        '200':
          description: File successfully received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateUrlResponse'
  '/document/getConfiguration/{id}':
    get:
      summary: Get configuration from redis by id
      operationId: GetConfigurationById
      tags:
      - configuration
      parameters:
      - name: id
        in: path
        description: Redis key
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Config found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateUrlRequest'
        '404':
          description: Config not found
components:
  schemas:
    GenerateUrlRequest:
      description: details about the required transaction
      required:
      - navigation
      properties:
        navigation:
          $ref: '#/components/schemas/Navigation'
        documentAccess:
          $ref: '#/components/schemas/EndpointAccess'
    GenerateUrlResponse:
      description: A temporary url for uploading documents
      properties:
        expiryDate:
          type: integer
          format: int64
        eFilingUrl:
          type: string
    EndpointAccess:
      type: object
      properties:
        url:
          type: string
        verb:
          type: string
          enum: [GET, POST]
        headers:
          type: object
          additionalProperties:
            type: string
    Navigation:
      required:
      - success
      - error
      - cancel
      properties:
        success:
          $ref: '#/components/schemas/Redirect'
        error:
          $ref: '#/components/schemas/Redirect'
        cancel:
          $ref: '#/components/schemas/Redirect'
    Redirect:
      required:
      - url
      properties:
        url:
          type: string
