openapi: 3.0.0
info:
  version: 0.3.0
  title: efiling-backend-demo
  description: Efiling Backend Demo
servers:
  - url: 'http://localhost:8080'
tags:
  - name: document
    description: Document Api
paths:
  '/document/{id}':
    get:
      summary: Get Document By Id
      operationId: GetDocumentById
      tags:
        - document
      parameters:
        - name: id
          in: path
          description: a document id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Config found
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Config not found
